asn: 65005
bgp_neighbors:
- neighbor: 10.0.3.9
  remote_as: 65005
  state: present
- neighbor: 10.0.1.16
  remote_as: 65000
  state: present
- neighbor: 10.0.2.16
  remote_as: 65000
  state: present
evpn_neighbors:
- neighbor: 10.0.250.1
  remote_as: 65000
  state: present
- neighbor: 10.0.250.2
  remote_as: 65000
  state: present
hostname: leaf9
interfaces:
- address: 10.0.1.17
  description: spine1
  interface: Ethernet11
  mask: /31
- address: 10.0.2.17
  description: spine2
  interface: Ethernet12
  mask: /31
- address: 10.0.3.8
  interface: Vlan4091
  mask: /31
loopback0_ip: 10.0.250.19
loopback1_ip: 10.0.255.19
side: left
